language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install -e .
    - pip install flake8

before_script:
    flake8 pynium tests

script:
    - py.test tests/ --webdriver PhantomJS
