language: python

python:
    - "2.7"
    - "3.4"

before_install:
    - "sudo apt-get install -qq xvfb"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5

install:
    - pip install -r tests-requirements.txt

before_script:
    flake8 pynium tests

script:
    - py.test tests/ -v
