build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"
install:
  - "%PYTHON%/Scripts/pip.exe install -r tests-requirements.txt"
test_script:
  - "%PYTHON%/Scripts/py.test tests -v"
