build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"
install:
  - "%PYTHON%/Scripts/pip.exe install -r tests-requirements.txt"
  # Install PhantomJS
  - cinst PhantomJS -y
test_script:
  - "%PYTHON%/Scripts/py.test tests -v --phantomjs-executable C:/Chocolatey/lib/PhantomJS.2.0.0/tools/phantomjs-2.0.0-windows/bin/phantomjs.exe"
